hw_project/hw_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls'))
]

hw_project/quotes/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.main, name='root'),
    path('<int:page>', views.main, name='root_paginate'),
    path('add-author/', views.add_author, name='add-author'),
    path('add-quote/', views.add_quote, name='add-quote'),
    path('author/<int:id_>', views.author, name='author'),
]

hw_project/users/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from . import views
from .forms import LoginForm

app_name = "users"

urlpatterns = [
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('signin/',
         LoginView.as_view(template_name='users/login.html', form_class=LoginForm, redirect_authenticated_user=True),
         name='signin'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout')
]

hw_project/quotes/models.py
from django.db import models


# Create your models here.

class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField()
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'quotes_author'

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=30, null=True, unique=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag, related_name='quotes')
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

hw_project/users/models.py
from django.db import models

# Create your models here.

hw_project/quotes/forms.py
from django.forms import ModelForm, CharField, DateField, TextInput, SelectDateWidget, SelectMultiple
from .models import Author, Quote


class AuthorForm(ModelForm):
    born_date = DateField(
        widget=SelectDateWidget(empty_label=("Choose Year", "Choose Month", "Choose Day"), years=range(1985, 2015)),
        input_formats=['%Y-%m-%d'],
    )

    class Meta:
        model = Author
        fields = ['description', 'fullname', 'born_date', 'born_location']
        widgets = {
            'description': TextInput(attrs={"class": "form-control", "id": "description"}),
        }

    def clean_born_date(self):
        born_date = self.cleaned_data['born_date']
        return born_date.strftime('%B %d, %Y')


class QuoteForm(ModelForm):
    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author']
        widgets = {
            'tags': SelectMultiple(attrs={"class": "form-control"}),
        }

hw_project/users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from django.forms import ModelForm, CharField, TextInput, FileInput, BooleanField, EmailInput, EmailField, PasswordInput


class RegisterForm(UserCreationForm):
    username = CharField(max_length=16, min_length=3, required=True, widget=TextInput(attrs={'class': 'form-control'}))
    email = EmailField(max_length=30, required=True, widget=EmailInput(attrs={'class': 'form-control'}))
    password1 = CharField(required=True, widget=PasswordInput(attrs={'class': 'form'}))
    password2 = CharField(required=True, widget=PasswordInput(attrs={'class': 'form'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginForm(AuthenticationForm):
    username = CharField(max_length=16, min_length=3, required=True, widget=TextInput(attrs={'class': 'form-control'}))
    password = CharField(required=True, widget=PasswordInput(attrs={'class': 'form'}))

    class Meta:
        model = User
        fields = ('username', 'password')

hw_project/quotes/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.

from .utils import get_mongo_db
from .models import Author, Quote
from .forms import AuthorForm, QuoteForm


def main(request, page=1):
    quotes = Quote.objects.all()
    per_page = 10
    paginator = Paginator(list(quotes), per_page=per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})


def author(request, id_):
    author_view = Author.objects.get(id=id_)
    return render(request, 'quotes/author.html', context={'author': author_view})


@login_required
def add_quote(request):
    form = QuoteForm()
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f"Нова цитата успішно створена")
            return redirect(to="quotes:add-quote")
    return render(request, 'quotes/add_quote.html', context={"form": form})


@login_required
def add_author(request):
    form = AuthorForm()
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f"Новий автор успішно створений")
            return redirect(to="quotes:add-author")
    return render(request, 'quotes/add_author.html', context={"form": form})

hw_project/users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages

from .forms import RegisterForm


# Create your views here.


class SignupView(View):
    template_name = 'users/register.html'
    form_class = RegisterForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to="quotes:root")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(request, f"Вітаємо {username}. Ваш акаунт успішно створено")
            return redirect(to="users:signin")
        return render(request, self.template_name, {"form": form})

hw_project/quotes/templates/quotes/add_author.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>Add new author</h2>
    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">fullname
                {{ form.fullname }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">born_date
                {{ form.born_date }}
            </label>
            <span>{{form.errors.born_date}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">born_location
                {{ form.born_location }}
            </label>
            <span>{{form.errors.born_location}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">description
                {{ form.description }}
            </label>
            <span>{{form.errors.description}}</span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}

hw_project/quotes/templates/quotes/add_quote.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>Add new author</h2>
    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}

hw_project/quotes/templates/quotes/author.html
{% extends 'quotes/base.html' %}

{% block content%}
<div class="author-details">
    <h3 class="author-title">{{author.fullname}}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{author.date_born}}</span>
        <span class="author-born-location">{{author.born_location}}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{author.description}}
    </div>
</div>
{% endblock %}

hw_project/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <div class="col-md-4 mt-3">
            <p>
                <a class="btn btn-info" href="{% url 'quotes:root' %}">Quotes</a>
               {% if user.is_authenticated %}
                <a href="{% url 'quotes:add-author' %}" class="btn btn-primary">Add Author</a>
                <a href="{% url 'quotes:add-quote' %}" class="btn btn-primary">Add Quote</a>
                <a href="{% url 'users:logout' %}" class="btn btn-primary">Logout</a>
               {% else %}
                    <a class="btn btn-primary" href="{% url 'users:signup' %}">SingUp</a>
                    <a class="btn btn-primary" href="{% url 'users:signin' %}">SingIn</a>
                {% endif %}
            </p>
        </div>
        {% if messages %}
            <div class="messages">
                {% for message in messages %}
                <span {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</span>
                {% endfor %}
            </div>
        {% endif %}
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

hw_project/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}
{% block content %}

<div class="row">
    {% for quote in quotes %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">
            {{ quote.quote }}
        </span>
        <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
        <a href="/author/{{quote.author.id}}">(about)</a>
        </span>
        <div class="tags">
            Tags:
            {% for tag in quote.tags.all %}
            <a class="tag" href="/tag/{{tag}}">
                {{tag}}
            </a>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
    <nav>
        <ul class="pager">
            <li class="previous">
                <a class ='{% if not quotes.has_previous %} disabled {% endif %}'
                   href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous
                </a>
            </li>
            <li class="next">
                <a class ='{% if not quotes.has_next %} disabled {% endif %}'
                   href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                    Next
                    <span aria-hidden="true">→</span></a>
            </li>

        </ul>
    </nav>
</div>

{% endblock %}

hw_project/users/templates/users/login.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>Login User</h2>

    {% if messages %}
    <div class="messages mt-3 mb-3">
        {% for message in messages %}
        <span {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</span>
        {% endfor %}
    </div>
    {% endif %}

    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password }}
            </label>
            <span>{{form.errors.password}}</span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}

hw_project/users/templates/users/logout.html
{% extends 'quotes/base.html' %}

{% block content %}

    <div class="container mt-3">
        <h1>Повертайтесь будь ласка!</h1>
    </div>

{% endblock %}

hw_project/users/templates/users/register.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>Register user</h2>
    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}
    <form method="post" >
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">username
            {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Email
            {{ form.email }}
            </label>
            <span>{{form.errors.email}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Password
            {{ form.password1 }}
            </label>
            <span>{{form.errors.password1}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Password repeat
            {{ form.password2 }}
            </label>
            <span>{{form.errors.password2}}</span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}